### ISSUE TITLE
Game crashing at bedrock layer of game and illuiminator/lumbinator randomly quit working

### ISSUE THREAD

**Issue by iamawesomebro** [DuelMonster/SuperMiner#10]
### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)

http://pastebin.com/ZM7dv3Jg

If there is anymore info I can provide please let me know, thank you.

**Comment by DuelMonster** [comment]
Thank you for the report.  I shall look in to this tonight.

**Comment by DuelMonster** [comment]
Hi,

Could you please try the latest version and let me know if this is still an issue?

[[1.11]-2.1.9.110](https://minecraft.curseforge.com/projects/superminer-unified/files)

Thanks
