### ISSUE TITLE
crash on load up(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [DuelMonster/SuperMiner#12]
### What should have happened
the game load as it did before the update
### What actually happened
it crashed
### What steps do we have to follow so we can reproduce the issue
update to super miner SuperMiner-[1.11.2]-2.1.10.115 and have forge1.11.2-2214
### Version of SuperMiner
SuperMiner-[1.11.2]-2.1.10.115
### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)
crash report: http://pastebin.com/GUj5NV6G

clinet latest log: [fml-client-latest (2).txt](https://github.com/DuelMonster/SuperMiner/files/706341/fml-client-latest.2.txt)

**Comment by SDUBZ** [comment]
also happens in actual 1.11 instance

crash report:
[crash-2017-01-15_12.25.04-client.txt](https://github.com/DuelMonster/SuperMiner/files/706343/crash-2017-01-15_12.25.04-client.txt)

fml client latest:
[fml-client-latest.txt](https://github.com/DuelMonster/SuperMiner/files/706345/fml-client-latest.txt)

**Comment by DuelMonster** [comment]
Oh bugger. Will sort asap

**Comment by DuelMonster** [comment]
Fix released
