### ISSUE TITLE
Lumbinator stops working after a time

### ISSUE THREAD

**Issue by ehmitchell3** [DuelMonster/SuperMiner#14]
Tried with and without mods, on a server setting and on a local setting. It seems after getting the getting wood cheevo, or when making an axe (even vanilla), the lumber-auto chop will stop working.

I have tried toggling the thing on and off. It works for the first couple trees on a completely new server/instance

**Comment by DuelMonster** [comment]
Are you still getting this issue with the latest release?

**Comment by Castellanox7** [comment]
So far, the Latest release seems to work. There's been another issue, but I'm narrowing it down to which of the mods I'm using, so this build may be 100% perfect.

Thanks again!

**Comment by DuelMonster** [comment]
Thank you.  closing this issue
