### ISSUE TITLE
[1.11.2]-2.1.17.128 - Random Crashes when Mining

### ISSUE THREAD

**Issue by digitalnoise** [DuelMonster/SuperMiner#15]
Granted, this may not be related strictly to Superminer, but it's something I've consistently encountered with SuperMiner enabled along with other mods.

The crashes are completely random, but always with the same java error: Exception in server tick loop.

The entire crash log is attached.
[crash-2017-02-11_18.42.49-server.txt](https://github.com/DuelMonster/SuperMiner/files/769021/crash-2017-02-11_18.42.49-server.txt)

**Comment by digitalnoise** [comment]
Additional Logs from Forge.
[fml-client-latest.txt](https://github.com/DuelMonster/SuperMiner/files/769023/fml-client-latest.txt)

**Comment by DuelMonster** [comment]
Should be fixed with latest release - [1.11.2]-2.1.18.129

**Comment by digitalnoise** [comment]
Unfortunately not - just crashed on me again, same errors as before, same mods as before - but I'm running then .129 update.

Logs are attached.
[crash-2017-02-12_18.52.17-server.txt](https://github.com/DuelMonster/SuperMiner/files/769831/crash-2017-02-12_18.52.17-server.txt)
[fml-client-latest-021217-1857.txt](https://github.com/DuelMonster/SuperMiner/files/769832/fml-client-latest-021217-1857.txt)

**Comment by DuelMonster** [comment]
Oh, bugger!  This is really difficult to lock down...  it's so random, I was playing it for an hour without any crashes before releasing...

I'll look at it again later.  Thanks

**Comment by DuelMonster** [comment]
Added another fix for this.  Please retry latest release:  2.1.19.130
