### ISSUE TITLE
[Feature Request] Speed modifier for Lumbinator

### ISSUE THREAD

**Issue by WesCook** [DuelMonster/SuperMiner#16]
After searching far and wide for a TreeCapitator replacement in 1.10, I found SuperMiner.  It intelligently looks for trees where solutions like Veinminer can't work.  My only concern is that it chops trees very quickly, which is not fantastic for balance.

Ideally I'd like to see something like TerraFirmaCraft, where the size of the tree determines the chopping time.  This could then be factored in with the normal tool speed, so Tinkers tools (and vanilla) still retain their speed modifier.

Would something like this be possible?  Thanks!

**Comment by DuelMonster** [comment]
I'm sure I could manage to wrangle something up to achieve your request.
At the moment I have a fixed block breaking speed, which could be modified quite easily to cater for tree size...
Once that change is made it should be fairly easy to cater for the speed modifiers as well.

I have a nasty crash issue to fix first, but this'll be the next thing on the list.

**Comment by WesCook** [comment]
That would be marvelous.  Thanks for your consideration!
