### ISSUE TITLE
Super miner still crashing server

### ISSUE THREAD

**Issue by Mugera500** [DuelMonster/SuperMiner#18]
### Version of SuperMiner: Newest (SuperMiner-[1.11.2]-2.1.20.131)
[crash-2017-02-17_05.04.56-server.txt](https://github.com/DuelMonster/SuperMiner/files/782272/crash-2017-02-17_05.04.56-server.txt)
[2017-02-15-4.log.gz](https://github.com/DuelMonster/SuperMiner/files/782275/2017-02-15-4.log.gz)

### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)

**Comment by DuelMonster** [comment]
Sorry about this!  I think I'm getting closer to getting this solved once and for all tho...
It all boils down to the minecraft code trying to do stuff with the item drops while I'm doing stuff on another thread.

Changes I made last night seem to be working well, I just need to modify it a bit more.  At the moment I'm getting Item drops from far away.  Last night I was mining at bed rock level and getting eggs when there were no chickens near by...

Hopefully I'll have a new version out either today or tomorrow.

Again, thank you for sticking with me on this.

**Comment by Mugera500** [comment]
no worries man, i want this to work out just as much as you do huehue.
i am just happy that you keep trying :)

take your time, there is no rush

**Comment by DuelMonster** [comment]
I'll be glad to get it resolved!  I have another project I'm eager to get back to...  ;-)

**Comment by DuelMonster** [comment]
New versions for 1.10.2, 1.11 & 1.11.2 just released.

Hoping this'll be\the last of the crashing issues.

@Mugera500 - let me no if I've cracked it this time.  Thanks

**Comment by Mugera500** [comment]
thought it worked for a second there, we both mined for a long time with diamond pickaxes, but as soon as i used a shovel on gravel, it crashed.
after restarting the server, then mining with pickaxes also made the server crash 
[2017-02-20-6.log.gz](https://github.com/DuelMonster/SuperMiner/files/786303/2017-02-20-6.log.gz)

http://pastebin.com/R7GfTy68

**Comment by DuelMonster** [comment]
Any errors or txt files can be just entered into a [Pastebin](http://pastebin.com/), makes life a little simpler...

Could you do me a favour and give me a copy of your SuperMiner.cfg file?  I'll use that to try and replicate your situation.

At least it lasted longer this time 😁
Thanks

**Comment by Mugera500** [comment]
this is the pastebin for my own minecraft:
http://pastebin.com/J7Cg6est

when i go to servers superminer config, then it is completly blank

let me know if you need anything else, just tried again and it crashed after about 5min

**Comment by DuelMonster** [comment]
Thanks, I'll look into it again as soon as I'm home from work.

FYI, the Server doesn't have it's own config options, they get synced from the Client side.

**Comment by SDUBZ** [comment]
this has also crashed me on my server
forge:1.11.2-2235
superminer: SuperMiner-[1.11.2]-2.1.26.266
crashreport:
[crash-2017-02-21_10.38.01-server.txt](https://github.com/DuelMonster/SuperMiner/files/790757/crash-2017-02-21_10.38.01-server.txt)

**Comment by DuelMonster** [comment]
New versions just released should hopefully solve this issue once and for all...

[1.11.2]-2.4.31.298
[1.11]-2.3.31.288
[1.10.2]-2.2.31.268

_PLEEEEEASE_ tell me it worked...?

**Comment by SDUBZ** [comment]
will test soon @DuelMonster :D

**Comment by SDUBZ** [comment]
@DuelMonster  tested singleplayer and still getting crash, so i presume it does also with serverside
[1.11.2]-2.4.31.298
[crash-2017-03-04_03.48.35-server.txt](https://github.com/DuelMonster/SuperMiner/files/817345/crash-2017-03-04_03.48.35-server.txt)

**Comment by DuelMonster** [comment]
OH FUDGE!

Thanks @SDUBZ.
I ran for well over an hour without crashes before releasing...
Could you give me a breif run through of what you did before the crash?

**Comment by SDUBZ** [comment]
well i turned on excavator and was just going around mining and then it was fine for awhile then boom it crashed when mining down near level 40 or less and crash

**Comment by SDUBZ** [comment]
oh heres a config to show all the tools that i marked down for usability it might help in future to finding bugs and compat issues :D 
[SuperMiner.zip](https://github.com/DuelMonster/SuperMiner/files/817525/SuperMiner.zip)

**Comment by Mugera500** [comment]
out from what i have experience, it seems to crash faster if you have built&played alot in the world you are using it in.

if i make a completely new SP world, i can mine for 20min+ without a crash
if i make a new server it works for around 3-5 min :/

it is really weird, but glad you havent given up yet huehue

**Comment by DuelMonster** [comment]
OK guys, lets try again...

[1.11.2]-2.4.32.306
[1.11]-2.3.32.290
[1.10.2]-2.2.32.270

I've slowed down the harvesting speed to be sure that MC can keep up with the block updates.

**Comment by DuelMonster** [comment]
Hey @Mugera500, @SDUBZ,

Any feedback on the latest release?

Thanks

**Comment by SDUBZ** [comment]
seems to be working so far :)

**Comment by DuelMonster** [comment]
Ooooo, here's hoping it holds up...  Thanks @SDUBZ

**Comment by SDUBZ** [comment]
no problem man :)

**Comment by Mugera500** [comment]
welp really thought it worked out there, i had no problem for over an hour, and then it sadly crashed again Q.Q

http://pastebin.com/AGrZE0dp

**Comment by DuelMonster** [comment]
Oh fudge...  Well at least it lasted much longer this time.

Thanks @Mugera500, I'll keep trying.
