### ISSUE TITLE
[Feature Request] Locking down features in modpacks

### ISSUE THREAD

**Issue by WesCook** [DuelMonster/SuperMiner#20]
I have another feature request for you, if you wouldn't mind.

In my previous post I mentioned that your mod had one of the few well-working lumber axe features, and I had planned to use it in the pack I'm working on.  I'm still using it, but I've discovered something doesn't work as I thought it did.

I was only planning on using the Lumberator feature, but I realized that clients can enable others such as Shaftanator even if they're not an OP.  As far as I can see it's all client-side.

This is problematic from a modpack (and server) perspective, as these features may be considered cheating if turned on.

Would it be possible to allow modpack authors (or servers) to lock down these features?  Either by respecting the config file on the server-side (over client), or some other protection?

Thank you.

**Comment by DuelMonster** [comment]
With the settings as they are currently ( client side ), it might take me a little time to lock it down on a server side basis, but not impossible.

I'm still trying to solve crash issues, but will defiantly add this to the list.

**Comment by WesCook** [comment]
Congrats on the release of MinersAdvantage.  :)

**Comment by DuelMonster** [comment]
Thanks Wes, hope it lives up to expectations.
