### ISSUE TITLE
[MC 1.10.2] Server crash when mining Certus Quartz Ore

### ISSUE THREAD

**Issue by AveoCross** [DuelMonster/SuperMiner#33]
### What should have happened
Ore vein should be mined properly.

### What actually happened
Server crashed when mined with Bronze Pickaxe from Mekanism.

### What steps do we have to follow so we can reproduce the issue
Mod is very picky for that issue. Sometimes it crashes, sometimes it works flawlessly. I think that issue is correlated to [THIS](https://github.com/DuelMonster/SuperMiner/issues/32).

### Version of SuperMiner
SuperMiner 2.2.32.270
Latest Forge

### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)
Server crash - https://pastebin.com/jEZGV6Su
No client crash and info in logs.

###Side-bug info
I found that lumbinator doesn't work very well. I mean - it works... If it works at all. Very often I cut a tree and nothing happens on server.

**Comment by DuelMonster** [comment]
Thank you for the crash report.

I am currently working on a full rewrite of my mod in order to rectify this crash.  I've run out of ideas on how to solve this issue and believe that a rewrite is my only remaining option.

So please bare with me.  It may take me a few weeks to complete.

**Comment by AveoCross** [comment]
Glad to hear that! I just thought that this mod is now abandoned.
I'm waiting for update! Mod is absolutely glorious (if works :D). So much important functions in one jar!

**Comment by DuelMonster** [comment]
Nope, most defiantly not abandoned ;)

IRL stuff getting in the way... 3 months into new job is taking it's toll.

**Comment by AveoCross** [comment]
No problem. I gonna be patient. c:
