### ISSUE TITLE
[Mod Support] Mystical Agriculture

### ISSUE THREAD

**Issue by GodsVictory** [DuelMonster/SuperMiner#4]
I'm not sure how superminer detects ore for the veinator, but it is missing ores added by mystical agriculture. Every time I add the ores manually to the config, they get overwritten.

**Comment by GodsVictory** [comment]
Also, it seems that basemetal ores are being added to the array even though I don't have the mod installed

**Comment by DuelMonster** [comment]
FYI, I shall be looking into this soon...

**Comment by DuelMonster** [comment]
I have identified the problem with Mystical Agriculture.

Turn out that the Ore blocks for this mod haven't been added to the Minecraft Ore Dictionary, which is what I use to identify valid Ores.

I've made changes to allow me to support these Ores and this fix will be within the next release.
I have I few more mod incompatibilities to add, so I shall put out a new release as soon as I have them added them as well.

DuelMonnster
